title: Mari Nagem
description: "site description"

url: https://2023.marinagem.com
baseurl: ''
exclude: [.git, .gitignore, .sass-cache, README.md]

markdown: kramdown
encoding: utf-8
port: 4234

defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"
      permalink: /:path/:basename/
  -
    scope:
      path: "pages/en"
    values:
      layout: "page"
      permalink: /en/:basename/
      lang: en
  -
    scope:
      path: "pages/pt"
    values:
      layout: "page"
      permalink: /pt/:basename/
      lang: pt
  -
    scope:
      path: "projects/en"
    values:
      layout: "project"
      permalink: /en/:basename/
      lang: en
  -
    scope:
      path: "projects/pt"
    values:
      layout: "project"
      permalink: /pt/:basename/
      lang: pt

social:
  facebook_user: "fbu"
  twitter_user: "twu"
