title: Mari Nagem
description: "site description"
keywords: "key, words"

url: https://2023.marinagem.com
# baseurl: "/2023"
baseurl: ""
exclude: [
  .git,
  .gitignore,
  Gemfile,
  Gemfile.lock,
  README.md,
  .sass-cache/,
  .jekyll-cache/,
  gemfiles/,
  node_modules/
]

sass:
  sass_dir: css/_sass

markdown: kramdown
encoding: utf-8
port: 4234

defaults:
  -
    scope:
      path: "pages/en"
    values:
      layout: "page"
      permalink: /:basename/
      lang: en
  -
    scope:
      path: "pages/pt"
    values:
      layout: "page"
      permalink: /pt/:basename/
      lang: pt
  -
    scope:
      path: "projects/en"
    values:
      layout: "project"
      permalink: /:basename/
      lang: en
  -
    scope:
      path: "projects/pt"
    values:
      layout: "project"
      permalink: /pt/:basename/
      lang: pt

social:
  facebook_user: "fbu"
  twitter_user: "twu"
