title: Mari Nagem
description: "site description"
keywords: "key, words"

url: https://2023.marinagem.com
# baseurl: "/2023"
baseurl: ""
exclude: [
  .git,
  .gitignore,
  Gemfile,
  Gemfile.lock,
  README.md,
  .sass-cache/,
  .jekyll-cache/,
  gemfiles/,
  node_modules/
]

sass:
  sass_dir: css/_sass

markdown: kramdown
encoding: utf-8
port: 4234

defaults:
  -
    scope:
      path: "pages/en"
    values:
      layout: "page"
      permalink: /:basename/
      lang: en
  -
    scope:
      path: "pages/pt"
    values:
      layout: "page"
      permalink: /pt/:basename/
      lang: pt
  -
    scope:
      path: "projects/en"
    values:
      layout: "project"
      permalink: /:basename/
      lang: en
  -
    scope:
      path: "projects/pt"
    values:
      layout: "project"
      permalink: /pt/:basename/
      lang: pt

social:
  facebook_user: "fbu"
  twitter_user: "twu"

# prose.io
prose:
  media: "imgs"
  ignore:
    - .gitignore
    - CNAME
    - _config.yml
    - _data
    - _includes
    - _layouts
    - _pages
    - css
    - js
    - imgs/favicons
    - imgs/swipebox
  metadata:
    projects:
      - name: "published"
        field:
          element: "hidden"
          value: "true"
      - name: "title"
        field:
          element: "text"
          label: "Page Title"
          placeholder: "Name of Project"
      - name: "description"
        field:
          element: "text"
          label: "Project Description"
          placeholder: "Site-specific installation"
      - name: "medium"
        field:
          element: "text"
          label: "Project Medium"
          placeholder: "Oil on canvas"
      - name: "dimensions"
        field:
          element: "text"
          label: "Project Dimensions"
          placeholder: "Variable Dimensions"
      - name: "year"
        field:
          element: "number"
          label: "Project Year"
          value: 2000
      - name: "cover"
        field:
          element: "text"
          label: "Cover Image URL"
          placeholder: "imgs/project-name/cover.jpg"
      - name: "category"
        field:
          element: "select"
          label: "Project Category"
          placeholder: "Choose Category"
          options:
            - name: 'sun'
              value: 'sun'
            - name: 'water'
              value: 'water'
            - name: 'florest'
              value: 'florest'
            - name: 'minerals'
              value: 'minerals'
            - name: 'machines'
              value: 'machines'
